### PR TITLE
Update values.yaml

### PR DESCRIPTION
**Pull request by ludydoo**
Fix bad values.yaml forceNameSpaced -> forceNamespaced

### CODE REVIEW

**Review by aramase — COMMENTED** [review]
@ludydoo Thank you for the PR. Could you make the change in https://github.com/Azure/aad-pod-identity/tree/master/manifest_staging/charts/aad-pod-identity instead of the `charts/` dir?

**Comment by chewong** [comment]
@ludydoo any update on this PR?

**Comment by ludydoo** [comment]
Looking into it

**Comment by ludydoo** [comment]
See  #874

**Pull request closed without merging**
