### PR TITLE
docs: reduce ambiguity in demo and role assignment docs

### PR DESCRIPTION
**Pull request by chewong**
**Reason for Change**:

**Issue Fixed**:

Fixes https://github.com/Azure/aad-pod-identity/issues/618.

cc @bq1756

**Notes for Reviewers**:

### CODE REVIEW

**Comment by elsesiy** [comment]
@chewong I think this PR should include an urgently needed reference to the need for `Network Contributor` when using Advanced Networking.

https://docs.microsoft.com/en-us/azure/aks/kubernetes-service-principal#networking

**Comment by elsesiy** [comment]
Here's what I have assigned on a newly provisioned cluster with advanced networking and managed identities to make everything work for both the `Kubelet Identity` (e.g. k8s-agentpool as well as Cluster Identity (cat /etc/kubernetes/azure.json):
```
Managed Identity Operator (MC_RG)
Virtual Machine Contributor (MC_RG)
Network Contributor (Deployment RG)
```

**Comment by chewong** [comment]
@elsesiy With https://github.com/Azure/aad-pod-identity/pull/559, I don't think the `Network Contributor` role is necessary anymore. I also tested with an AKS cluster with its VNet in a different resource group and aad-pod-identity works without assigning that particular role.

**Comment by elsesiy** [comment]
@chewong I looked at the diff but don't see why this would solve this just yet. You'll run into this issue in multiple other occasions such as deploying an internal ALB as well so I needed it for sure.

**Comment by aramase** [comment]
@elsesiy This is the [PR](https://github.com/Azure/aad-pod-identity/pull/522) that switches to using `PATCH` instead of VM `CreateOrUpdate`. `PATCH` only updates the identity config in the VM/VMSS. Are you using v1.6.0? What is the error you're seeing in MIC?

**Comment by elsesiy** [comment]
@aramase I updated to `1.6.0` yesterday and haven't been seeing any errors since except for when deploying an internal load balancer. This case is unrelated to aad-pod-identity so I assume we're good here

**Pull request merged**
