### PR TITLE
helm: correct spec field for AzureIdentityBinding

### PR DESCRIPTION
**Pull request by chewong**
Signed-off-by: Ernest Wong <chuwon@microsoft.com>

**Reason for Change**:

Fiixes #1068.

**Requirements**

- [x] squashed commits
- [x] included documentation
- [x] added unit tests and e2e tests (if applicable). See [test standard](https://github.com/Azure/aad-pod-identity/blob/master/CONTRIBUTING.md#test-standard) for more details.
- [x] ran `make precommit`

**Issue Fixed**:

**Please answer the following questions with yes/no**:

Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?

- [ ] yes
- [x] no

**Notes for Reviewers**:

### CODE REVIEW

**Review by aramase — APPROVED** [review]

**Comment by riddhi2910** [comment]
@chewong Could you please let me know, when will you release this image version? We are having the same issue, would like to get this resolved as soon as possible.

**Comment by chewong** [comment]
@riddhi2910 we are planning to release 1.8.1 next week. Meanwhile, you should be able to use v1.8.0 with chart version 4.0.0 by having `--set mic.tag=v1.8.0 --set nmi.tag=v1.8.0` during helm install/upgrade

**Comment by riddhi2910** [comment]
@chewong Thanks a lot! Should use mic.tag=1.8.1 and nmi=.1.8.1 with the chart 4.1.1?

**Comment by chewong** [comment]
You can continue using app version 1.8.0 since we didn't bump it for the 4.1.1 chart release.

**Comment by riddhi2910** [comment]
Sorry Let me clarify, We are already using 1.8.0 and 4.1.0, and were facing
the above error which solved in #1069, I want to make sure if the issue is
fixed in 1.8.0 or 1.8.1?

**Comment by chewong** [comment]
Since it's a helm-related change, it's not included in the next release. You can try `helm repo update` and `helm upgrade` to upgrade your chart.

**Comment by riddhi2910** [comment]
Ok, thanks for the clarification.

**Pull request merged**
