### PR TITLE
Update E2E to run tests based on generated images

### PR DESCRIPTION
**Pull request by pjbgf**
The former E2E tests were being executed against the publicly available docker images, instead of using the images generated locally and published into custom container registry. Making it easier for new contributors to support this project.

Environment Variables required:

- REGISTRY
- SUBSCRIPTION_ID
- RESOURCE_GROUP
- AZURE_CLIENT_ID

Once the environment variables are set, changes can be built and tested in a cluster with: 
`make build && make image && make push && make e2e`

### CODE REVIEW

**Comment by pjbgf** [comment]
Fixes #132

**Comment by kkmsft** [comment]
Thank you! @pjbgf for this PR. I have merged the e2e fixes PR. Can you please rebase/merge this PR so that we can get moving on merging this.

**Comment by CecileRobertMichon** [comment]
closing in favor of #218

**Pull request closed without merging**
