### PR TITLE
Adds a default affinity rule to values.yaml

### PR DESCRIPTION
**Pull request by JasonWhall**
**Reason for Change**:

Adds a default affinity rule to values.yaml
- Uses preferred rule instead of required to not hard fail scheduling on single node clusters

**Requirements**

- [x] squashed commits
- [x] included documentation
- [x] added unit tests and e2e tests (if applicable). See [test standard](https://github.com/Azure/aad-pod-identity/blob/master/CONTRIBUTING.md#test-standard) for more details.
- [x] ran `make precommit`

**Issue Fixed**:

#1058

**Please answer the following questions with yes/no**:

Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?

- [ ] yes
- [x] no

### CODE REVIEW

**Review by chewong — COMMENTED** [review]
Thanks for the contribution. Could you make the change in `manifest_staging` folder instead?

**Comment by JasonWhall** [comment]
@chewong sure, updated!

**Review by aramase — COMMENTED** [review]
Could you also add the default `affinity` in the [configuration table](https://github.com/Azure/aad-pod-identity/tree/master/manifest_staging/charts/aad-pod-identity#configuration)?

**Comment by psiservices-jwhalley** [comment]
@aramase - Done. It's notoriously hard to get a code block into a table so I've opted for just a description of the rule if that's ok?

**Review by chewong — APPROVED** [review]

**Pull request merged**
