### PR TITLE
Upgrade to go1.14

### PR DESCRIPTION
**Pull request by elsesiy**
Update project files to go1.14
Simplify azure-pipelines.yaml
Remove unnecessary go build args

### CODE REVIEW

**Comment by elsesiy** [comment]
@aramase Can you trigger Azure Pipelines please? I don't have sufficient privileges...thanks!

**Comment by elsesiy** [comment]
@aramase Thanks, built successfully! Please let me know if you have any review remarks

**Comment by elsesiy** [comment]
@aramase Done! I also removed the `workingDirectory` stanza completely which should default to the same dir. Can we get another azp run just to make sure? Thanks!

**Comment by aramase** [comment]
thank you for the PR @elsesiy!

**Pull request merged**
