### PR TITLE
Add back entrypoints to images

### PR DESCRIPTION
**Pull request by cpuguy83**

### CODE REVIEW

**Comment by cpuguy83** [comment]
OH maybe should not have updated the helm chart until new images are available.

**Comment by cpuguy83** [comment]
Should I just build and push a new set over existing tags?

/cc @khenidak

**Comment by cpuguy83** [comment]
Maybe a 1.4.1 and 1.3.1 respectively?

**Comment by kkmsft** [comment]
@cpuguy83 - I think we should revert the change, bring back only entry point change and then change the deployment files before the next release.

**Comment by kkmsft** [comment]
May be we should think of releasing the deployment file or modify the release notes to state the deployment to use.. that way there is no confusion..

**Pull request merged**
