### PR TITLE
docs: update invalid URLs in website

### PR DESCRIPTION
**Pull request by chewong**
Signed-off-by: Ernest Wong <chuwon@microsoft.com>

**Reason for Change**:

- updated URLs to point to https://azure.github.io/aad-pod-identity
- removed duplicated markdowns in repo

**Requirements**

- [x] squashed commits
- [x] included documentation
- [x] added unit tests and e2e tests (if applicable). See [test standard](https://github.com/Azure/aad-pod-identity/blob/master/CONTRIBUTING.md#test-standard) for more details.
- [x] ran `make precommit`

**Issue Fixed**:

**Please answer the following questions with yes/no**:

Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?

**Notes for Reviewers**:

### CODE REVIEW

**Comment by phillipgibson** [comment]
On the netlify preview it looks like the get started link is still broken. Maybe we just remove the landing page and just have it land on the docs index.

**Comment by chewong** [comment]
@phillipgibson Fixed. PTAL.

**Comment by phillipgibson** [comment]
I crawled the site and it looks good. Merge when ready.

**Review by phillipgibson — APPROVED** [review]
Looks good. All links working.

**Pull request merged**
