### PR TITLE
#444 Support for Helm 3

### LINKED ISSUE #444: Support for Helm 3
Helm 3 has been released and it would be good if the Chart for aad-pod-identity was updated

**Explain why AAD Pod Identity needs it**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Helm 3 contains changes to how crds works and thus we get the following error

> manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "AzureIdentity" in version "aadpodidentity.k8s.io/v1", unable to recognize "": no matches for kind "AzureIdentityBinding" in version "aadpodidentity.k8s.io/v1"]

### PR DESCRIPTION
**Pull request by BzSpi**
**Reason for Change**:

This PR makes the Helm chart compatible with Helm 3 by keeping compatibility with Helm 2.

**Issue Fixed**:

Fixes #444 

**Notes for Reviewers**:
I'm not sure I've used to good way to handle the chart version, let me know.

### CODE REVIEW

**Comment by unguiculus** [comment]
Thanks for fixing this. We (maintainer here) have an issue over at the community charts repo to track Helm 3 compatibility. This PR fixes it along those lines.

See https://github.com/helm/charts/issues/19008

Any chance this can get merged soon? @BzSpi Could you fix conflicts?

**Comment by BzSpi** [comment]
Hi @unguiculus, thanks for your feedback, I've rebased my branch.

Let me know if modifying the chart version should be part of this MR or not.

**Comment by unguiculus** [comment]
@BzSpi Maybe my comment was a little bit misleading. I'm a Helm maintainer, not a maintainer here. Sorry, if this came across wrong. I don't know how chart versioning is handled here but IMHO it's correct to increment the version.

**Pull request merged**
