### PR TITLE
Add priority classes to the Helm chart.

### PR DESCRIPTION
**Pull request by iverberk**
**Reason for Change**: Add the possibility to specify a priority class for the deployment and daemonset.

**Issue Fixed**: N/A

**Notes for Reviewers**: N/A

### CODE REVIEW

**Comment by aramase** [comment]
@iverberk Can you please address the comments I posted above. I can then approve and merge the PR.

**Comment by iverberk** [comment]
Hi @aramase, I will fix the PR. Why is it only restricted to kube-system namespace? Are you referring to the 'critical' class: https://github.com/kubernetes/kubernetes/pull/76310 ?

**Comment by aramase** [comment]
@iverberk Correct, I'm referring to the `system-cluster-critical` and `system-node-critical`.

**Pull request merged**
