### PR TITLE
Add linting tools to CI workflow

### PR DESCRIPTION
**Pull request by elsesiy**
I noticed there's no linting performed in any capacity, so I added `golangci-lint` and `misspell` by creating a new module and using the build tag `+tools` to ensure it's not part of the regular build process.

This is only the first step. Running `make lint` reveals there's a lot to clean up.

Ref: https://github.com/Azure/aad-pod-identity/issues/571

### CODE REVIEW

**Comment by elsesiy** [comment]
@aramase Mind triggering a `/azp run` for me? I'll reference the build output here after to show the linting results

**Comment by elsesiy** [comment]
@aramase I decided against putting it into the CI for now, it's just too many things to clean up before. Please take a look at the current state of the PR and let me know if it misses anything.

I'll create a follow-up PR with fixes for the linting errors.

**Comment by elsesiy** [comment]
@aramase Anything missing from your perspective?

**Comment by aramase** [comment]
/azp run

@elsesiy Thank you. It looks good. I'll review and merge once I get 1.6 release out for pod-identity this week.

**Comment by aramase** [comment]
@elsesiy Can you rebase the PR when you get a chance?

**Comment by chewong** [comment]
@elsesiy thanks for the PR. Could you resolve the merge conflicts and rebase your branch?

**Comment by elsesiy** [comment]
@chewong @aramase Done

**Pull request merged**
